### ISSUE TITLE
serialport + nodewebkit version 0.10.2

### ISSUE THREAD

**Issue by redramster** [voodootikigod/node-serialport#374]
I am trying to work with node-webkit's latest version which is built on nodes 0.11.13
I understand from your comment that there is a problem but I was not sure on its nature. However, I was able to compile serialport using nw-pre-gyp but when I try to use it (require("serialport") I get the following error:
Error: The specified procedure could not be found.
 d:\Edu Quest (x86)\node_modules\serialport\build\serialport.node
message: "The specified procedure could not be found.
↵d:\Edu Quest (x86)\node_modules\serialport\build\serialport.node"
stack: "Error: The specified procedure could not be found.
↵d:\Edu Quest (x86)\node_modules\serialport\build\serialport.node↵    at Error (native)↵    at Module.load (module.js:352:32)↵    at Function.Module._load (module.js:308:12)↵    at Module.require (module.js:360:17)↵    at require (module.js:376:17)↵    at Object.<anonymous> (D:\Edu Quest (x86)\node_modules\serialport\serialport.js:12:25)↵    at Module._compile (module.js:452:26)↵    at Object.Module._extensions..js (module.js:470:10)↵    at Module.load (module.js:352:32)↵    at Function.Module._load (module.js:308:12)"

I tried to compile using nodes 0.11.10 using nw-pre-gyp. compile was successful, but I still get the same error.

Is there any workaround?
Thanks
Ramster

**Comment by matthova** [comment]
@konsumer That was awesome. Thank you!
Mac works. On to windows

**Comment by mike1808** [comment]
HI. I faced this issue too.
Here is my logs and versions
node - v0.12.0
node-pre-gyp - v0.6.4
serialport - 1.5.0
nw.js - v0.11.5

Here is my log from npm 
```log
    d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(200): error C2039: 'SetCounterFunction' : is not a
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(200): error C2039: 'SetCounterFunction' : is not a
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(200): error C3861: 'SetCounterFunction': identifie
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(200): error C3861: 'SetCounterFunction': identifie
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(205): error C2039: 'SetCreateHistogramFunction' :
	j]
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(205): error C2039: 'SetCreateHistogramFunction' :
	j]
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(205): error C3861: 'SetCreateHistogramFunction': i
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(205): error C3861: 'SetCreateHistogramFunction': i
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(210): error C2039: 'SetAddHistogramSampleFunction'
	proj]
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(210): error C2039: 'SetAddHistogramSampleFunction'
	proj]
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(210): error C3861: 'SetAddHistogramSampleFunction'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(210): error C3861: 'SetAddHistogramSampleFunction'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(214): error C2039: 'IdleNotification' : is not a m
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(214): error C2039: 'IdleNotification' : is not a m
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(214): error C3861: 'IdleNotification': identifier
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(214): error C3861: 'IdleNotification': identifier
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(218): error C2039: 'LowMemoryNotification' : is no
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(218): error C2039: 'LowMemoryNotification' : is no
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(218): error C3861: 'LowMemoryNotification': identi
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(218): error C3861: 'LowMemoryNotification': identi
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(222): error C2039: 'ContextDisposedNotification' :
	oj]
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(222): error C2039: 'ContextDisposedNotification' :
	oj]
	          c:\Users\Michael\.nw-gyp\0.11.2\deps\v8\include\v8.h(4699) : see declaration of 'v8::V8'
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(222): error C3861: 'ContextDisposedNotification':
	d:\projects\serialport-nw-tester\node_modules\serialport\node_modules\nan\nan.h(222): error C3861: 'ContextDisposedNotification':
	..\src\serialport.cpp(76): warning C4344: behavior change: use of explicit template arguments results in call to 'v8::Local<T> Nan
	]
```

**Comment by Mithgol** [comment]
@mike1808 serialport 1.5.0 [uses](https://github.com/voodootikigod/node-serialport/blob/1961bee4434bc981da7f3365d20ad30427d63333/package.json#L48) nan 1.6.2, and nan (since version 1.6) requires a newer nw.js version (see rvagg/nan#238).

Try nw.js [version 0.12.0-alpha3](http://dl.nwjs.io/v0.12.0-alpha3/).

**Comment by Deliaz** [comment]
**konsumer**, thanx for the https://github.com/voodootikigod/node-serialport/issues/374#issuecomment-66543928
The only advice that helped me

**Comment by jacobrosenthal** [comment]
Huge thanks to everyone above for ironing out this process for me!

I did this today and wanted to update @konsumer's wonderful wrap up https://github.com/voodootikigod/node-serialport/issues/374#issuecomment-66543928

with the changes needed from  https://github.com/voodootikigod/node-serialport/issues/374#issuecomment-75040329

Grab [@konsumer's code](https://gist.github.com/konsumer/a1c5c8471a51d9077ca0), put into a directory nwktest, cd to that directory

First nobody mentioned installing these globally but they're being referenced that way, so I wanted to:
```
npm i -g node-pre-gyp
npm i -g nw-gyp
```
Then as stated:
```
npm install
```
Next go to the serialport source directory and rebuild there with the 12.0 alpha target
```
cd node_modules/serialport
node-pre-gyp rebuild --runtime=node-webkit --target=0.12.0-alpha3
```
Note I didnt have to move things around anymore. Then download and unpack the [nwjs executable](http://dl.nwjs.io/v0.12.0-alpha3/) and run it against the nwktest directory
```
/Users/jacobrosenthal/Downloads/nwjs-v0.12.0-alpha3-osx-x64/nwjs.app/Contents/MacOS/nwjs ~/Desktop/nwktest
```

**Comment by mn1aC** [comment]
On windows (32bits)

`npm install serialport
cd /node_modules/serialport
node-pre-gyp rebuild --runtime=node-webkit --target=0.12.0 --target_arch=ia32`

I get the following error:
`node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (Error: sp
awn node-gyp.cmd ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Electro Cornel
is\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\compile.js:67:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:107:17)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1065:12)
node-pre-gyp ERR! stack     at child_process.js:1137:20
node-pre-gyp ERR! stack     at process._tickCallback (node.js:355:11)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\Electro Cornelis\\AppData\\Roaming\
\npm\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "rebuild" "--runtime=node-w
ebkit" "--target=0.12.0" "--arch=ia32"
node-pre-gyp ERR! cwd C:\Users\Electro Cornelis\Desktop\nw\nw\nw\node_modules\se
rialport
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)`

**Comment by tsangpozheng** [comment]
On Windows 7 64bits

CMD:
node_modules\serialport>node-pre-gyp rebuild --runtime=node-webkit --target=0.12.0 --target_arch=ia32

OUTPUT:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.4
node-pre-gyp info using node@0.10.35 | win32 | x64
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (Error: sp
awn ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\
AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\compile.js:67:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:95:17)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:818:12)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\Administrator\\AppData\\Roaming\\np
m\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "rebuild" "--runtime=node-webk
it" "--target=0.12.0" "--target_arch=ia32"
node-pre-gyp ERR! cwd D:\workspace\shangweiji\node_modules\serialport
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd clean' (Error: spawn ENOENT)

**Comment by camposcristian90** [comment]
Instead of the rebuild command, i've used:

node-pre-gyp clean
nw-gyp configure --target=0.12.0-alpha3
node-pre-gyp build --runtime=node-webkit --target=0.12.0-alpha3

I think now building correctly, but if I execute the app now I've got an error on js console saying:

Uncaught Error: Cannot find module 'serialport'

**Comment by konsumer** [comment]
Try doing the rename step (as in my above comment) for that version.  If the build is succeeding, but it's not able to find it, you can see the full path that it's looking for in the error.

**Comment by PeteSteu** [comment]
My way to get it running on windows 7 64bit
- Install MS Visual Studio Express 2013 for Desktop
- Install Python 2.7.6
- Add Python to the path
- Reboot
- Open the 'Visual Studio Command Prompt' (Developer Eingabeaufforderung für VS2013)
- Install nw-gyp with this command: `npm install nw-gyp -g`
- Install node-pre-gyp with this command: `npm install node-pre-gyp -g`
- Change to my working directory (project directory)
- Install serialport with this command: `npm install serialport`
- Switch to the serialport modul directory: `cd node_modules\serialport`
- Make a clean: `node-pre-gyp clean`
- Configure the build process: `node-pre-gyp configure --runtime=node-webkit --target=0.12.0`
- Build the module for node-webkit: `node-pre-gyp build --runtime=node-webkit --target=0.12.0`
- After all I have to change the directoryname from `/node_modules/serialport/build/serialport/v1.6.3/Release/node-webkit-v0.12.0-win32-x64\` to 
`/node_modules/serialport/build/serialport/v1.6.3/Release/node-webkit-v43-win32-x64\`

That's it and it worked perfectly for me.

**Comment by voodootikigod** [comment]
This is due to the way nw.js/node-webkit changes the Node-ABI. This is not an issue with serialport, review this for more information: https://github.com/nwjs/nw.js/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons

Closing

**Comment by dennisdevulder** [comment]
Sorry to rip open old wounds but after cracking my head over this for a while I found a fix for myself.

    cd your_node_webkit_path
    npm install serialport
    npm install node-pre-gyp -g
    cd node_modules/serialport
    node-pre-gyp rebuild --runtime=node-webkit --target=0.12.0

And it works.

**Comment by xypaul** [comment]
@dennisdevulder thanks so much this one helped me out soooo much :)

**Comment by hugocruz** [comment]
@dennisdevulder Thanks, it worked for me. I needed also ```npm install -g nw-gyp.```
