### ISSUE TITLE
Failed to compile with iojs 1.5, 1.7 and 2.0?

### ISSUE THREAD

**Issue by 0x80** [voodootikigod/node-serialport#534]
I must be missing something here. I've tried all three and non are working for me. Below is the output from 1.5. What is wrong with this picture?

```
> serialport@1.7.3 install /Users/me/tmp/serialtest/node_modules/serialport
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
../src/serialport_unix.cpp:186:7: error: redefinition of 'fd'
  int fd = open(data->path, flags);
      ^
../src/serialport_unix.cpp:156:15: note: previous definition is here
int setup(int fd, OpenBaton *data) {
              ^
../src/serialport_unix.cpp:710:20: warning: comparison of array 'device.locationId' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.locationId != NULL) {
            ~~~~~~~^~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:713:20: warning: comparison of array 'device.vendorId' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.vendorId != NULL) {
            ~~~~~~~^~~~~~~~    ~~~~
../src/serialport_unix.cpp:716:20: warning: comparison of array 'device.productId' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.productId != NULL) {
            ~~~~~~~^~~~~~~~~    ~~~~
../src/serialport_unix.cpp:719:20: warning: comparison of array 'device.manufacturer' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.manufacturer != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
../src/serialport_unix.cpp:722:20: warning: comparison of array 'device.serialNumber' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if (device.serialNumber != NULL) {
            ~~~~~~~^~~~~~~~~~~~    ~~~~
5 warnings and 1 error generated.
make: *** [Release/obj.target/serialport/src/serialport_unix.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/me/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/me/.nvm/versions/io.js/v1.5.1/bin/iojs" "/Users/me/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/me/tmp/serialtest/node_modules/serialport/build/serialport/v1.7.3/Release/node-v43-darwin-x64/serialport.node" "--module_name=serialport" "--module_path=/Users/me/tmp/serialtest/node_modules/serialport/build/serialport/v1.7.3/Release/node-v43-darwin-x64"
gyp ERR! cwd /Users/me/tmp/serialtest/node_modules/serialport
gyp ERR! node -v v1.5.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/me/.nvm/versions/io.js/v1.5.1/bin/iojs /Users/me/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/tmp/serialtest/node_modules/serialport/build/serialport/v1.7.3/Release/node-v43-darwin-x64/serialport.node --module_name=serialport --module_path=/Users/me/tmp/serialtest/node_modules/serialport/build/serialport/v1.7.3/Release/node-v43-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/me/tmp/serialtest/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:984:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/me/tmp/serialtest/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/me/tmp/serialtest/node_modules/serialport
node-pre-gyp ERR! node -v v1.5.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/Users/me/.nvm/versions/io.js/v1.5.1/bin/iojs /Users/me/.nvm/versions/io.js/v1.5.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/me/tmp/serialtest/node_modules/serialport/build/serialport/v1.7.3/Release/node-v43-darwin-x64/serialport.node --module_name=serialport --module_path=/Users/me/tmp/serialtest/node_modules/serialport/build/serialport/v1.7.3/Release/node-v43-darwin-x64' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/me/.nvm/versions/io.js/v1.5.1/bin/iojs" "/Users/me/.nvm/versions/io.js/v1.5.1/bin/npm" "install" "serialport"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.7.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.7.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/tmp/serialtest/npm-debug.log
```

**Comment by 0x80** [comment]
I'm confused. I tried them serveral times and now its working :/ Bleh
